# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 419d2b3c87feba338885c19ce683384846e1f2096892653e51a0345e4c047d13fa053887deee2904c276eecbc7a8cf6b3dbc38af5566ac41213255e9239b5a88

test:
  secret_key_base: bc67c15bc052ee8a9ed5f95515c94dd803cfbdb06c75737a42424f5ab0e4c922a811b95b31a22c382e8c19ba0fc73828ba939ff739510d3e7b3f3b324ecda13e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
